# the token of the bot you get from t.me/botfather (type: str)
bot_token: "1705381120:AAFItE7QsZZHCFnzbdqtCzZnrwhf_J0CqQI"

# the name of the database (type: str)
db_path: "mongodb://antXpras:antxpras@cluster0.8i471.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"

# a list containing the telegram ids of the admins of the bot (type: ids are int)
admins: 
- 1691090729
